// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqpRA15VsHOPkNqOx3191NbNCaHpfex2Y',
    appId: '1:457386901748:web:9fd4f26e6df095f00f5ea1',
    messagingSenderId: '457386901748',
    projectId: 'app-pokemon-a1ab6',
    authDomain: 'app-pokemon-a1ab6.firebaseapp.com',
    storageBucket: 'app-pokemon-a1ab6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXe25bJrEo8_vhlOmi-wXt1FxJv-PLJXE',
    appId: '1:457386901748:android:4ea8319404ce5f490f5ea1',
    messagingSenderId: '457386901748',
    projectId: 'app-pokemon-a1ab6',
    storageBucket: 'app-pokemon-a1ab6.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGllTb5GbmQJVZ0-EUkisUc9luMoAB2Uw',
    appId: '1:457386901748:web:bdadde399c95fa980f5ea1',
    messagingSenderId: '457386901748',
    projectId: 'app-pokemon-a1ab6',
    authDomain: 'app-pokemon-a1ab6.firebaseapp.com',
    storageBucket: 'app-pokemon-a1ab6.firebasestorage.app',
  );

}